
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[214] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       62,   60,   59,   59,   58,   49,   25,   39,   60,   53,
       54,   37,   35,   50,   36,   60,   38,   23,   23,   33,
       42,   46,   44,   57,   55,   56,   34,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   51,   57,   52,    3,    2,    7,    6,    7,   28,
       29,   26,   27,   30,   30,   31,   48,   40,   22,   24,
        4,    1,   24,   23,   23,    0,    0,   43,   47,   45,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   22,   11,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,   41,    5,
        0,   24,    0,   24,   23,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   12,   57,   57,   57,
       18,   22,    0,   57,   57,   57,   57,   57,   57,   57,
       13,    0,   24,   21,   57,   57,   57,   57,   57,   10,
       57,   57,    0,   15,   57,   57,    0,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,    0,
       57,   57,    0,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,    0,   57,    0,   57,    9,   57,
       20,   57,   57,   19,    0,   57,   17,    8,   57,   57,

        0,   57,    0,   57,    0,    0,   57,    0,    0,   14,
        0,   16,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   18,   18,   18,   18,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   30,
       29,   29,   29,   29,   29,   29,   29,   31,   29,   29,
       32,   33,   34,    1,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   29,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    1,    1,    1,    1,    2,    2,    2,    3,    3,
        3,    1,    1,    1,    3,    2,    2,    2,    2,    2,
        2,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        2,    1
    } ;

static const flex_int16_t yy_base[221] =
    {   0,
        0,    0,  197,  177,   60,   61,   62,   63,   94,  141,
      179,  803,  803,  803,  803,  151,  803,  803,  164,  803,
      803,  803,  158,  803,  144,   56,   67,  176,   70,  803,
      133,  128,  127,   82,  803,  803,   87,   95,  110,   82,
      112,  118,   43,  128,   83,  156,  113,  162,  174,  177,
      131,  803,  165,  803,  803,  803,  803,  803,  134,  803,
      803,  803,  803,  803,  803,  803,  803,  803,  803,  220,
      803,  803,  225,  249,  263,  237,    0,  803,  803,  803,
      254,  175,  243,  252,  251,  262,  264,  274,  273,  275,
      284,  285,  293,  297,  294,  306,  314,  316,  317,  326,

      335,  338,  336,  346,  348,  358,  356,  361,  367,  803,
      402,  407,  412,  419,    0,  424,  410,  412,  416,  415,
      418,  427,  433,  438,  439,  463,  443,  454,  444,  448,
      460,  459,  108,  465,  476,  478,  480,  491,  488,  500,
      489,  534,  539,  525,  526,  527,  530,  528,  543,  546,
      548,  549,   94,  551,  554,  564,   71,  569,  575,  574,
      584,  585,  587,  595,  603,  606,  604,  607,  624,   69,
      616,  622,   78,  626,  628,  637,  639,  643,  647,  656,
      659,  662,  667,  703,   73,  668,   58,  689,  690,  691,
      692,  708,  695,  735,   60,  721,  803,  700,  731,  725,

       40,  726,   66,  736,   37,   28,  727,   32,   30,  803,
       26,  803,  803,  786,  789,  792,  795,  797,   65,  799
    } ;

static const flex_int16_t yy_def[221] =
    {   0,
      213,    1,  214,  214,  215,  215,  216,  216,  217,  217,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  218,  213,  213,  218,  218,  218,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,  213,   39,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  219,  213,  213,  213,
      220,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   39,  213,
      213,  213,  213,  213,  219,  220,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,  213,   39,   39,   39,   39,   39,   39,   39,
       39,  213,  213,   39,   39,   39,   39,   39,   39,   39,
       39,   39,  213,   39,   39,   39,  213,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,  213,
       39,   39,  213,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,  220,  213,   39,  213,   39,   39,   39,
       39,   39,   39,  220,  213,   39,  213,   39,   39,   39,

      213,   39,  213,   39,  213,  213,   39,  213,  213,  213,
      213,  213,    0,  213,  213,  213,  213,  213,  213,  213
    } ;

static const flex_int16_t yy_nxt[866] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   30,   31,   32,   33,   34,   34,   34,   34,   34,
       34,   35,   12,   36,   37,   34,   38,   39,   40,   41,
       42,   43,   34,   44,   34,   34,   34,   45,   34,   46,
       47,   48,   49,   50,   34,   51,   34,   34,   34,   52,
       53,   54,   58,   58,   61,   61,  115,   62,   62,  212,
       59,   59,   70,   70,   70,   70,   70,   71,   82,  211,
      210,  209,   72,  208,   73,   82,   75,   75,   75,   75,
       75,  206,   95,  205,   63,   63,   65,   76,   81,   81,

       81,   81,   81,   81,   81,   81,   81,   81,  201,   76,
      197,   81,   81,   81,   81,   81,  195,   82,   99,  187,
      185,   88,  173,  170,   82,   82,   81,   81,   81,   81,
       81,   82,   82,  157,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   65,   83,   85,   84,   82,  101,  110,
       80,   79,   86,   90,   82,   82,   78,   69,   89,   87,
       82,   82,   82,   82,   91,   92,  108,   93,   96,   69,
       82,   68,   94,   82,   67,   97,   98,   82,  213,   56,
       82,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       73,   82,   74,   74,   74,   74,   75,  102,   82,   56,

       82,  103,  213,   76,   82,   82,   77,   82,  100,   82,
       82,   82,   82,  104,   82,   76,   82,   82,  213,   82,
      213,  213,  213,   82,   82,  109,   82,  105,  213,  213,
      106,  213,  213,   77,  213,  107,   70,   70,   70,   70,
       70,  112,  112,  112,  112,  112,  213,  111,  113,  213,
      113,  213,   76,  114,  114,  114,  114,  114,  213,  111,
      213,  213,  213,   73,   76,   74,   74,   74,   74,   75,
       81,   81,   81,   81,   81,  213,   76,   73,   82,   75,
       75,   75,   75,   75,  213,   82,   82,   82,   76,  213,
       76,  118,  117,   82,   82,  213,  213,  120,  213,   82,

       82,   82,   76,  119,   82,  213,   82,  213,   82,   82,
       82,   82,  121,   82,  122,   82,   82,   82,  213,   82,
       82,  124,   82,   82,   82,  123,   82,   82,   82,   82,
      213,  213,   82,  125,   82,   82,   82,  213,  126,   82,
      133,   82,   82,   82,  127,  128,   82,  129,   82,   82,
      213,   82,   82,  213,  213,   82,   82,  213,   82,   82,
      213,   82,  213,   82,  130,   82,   82,  132,   82,  131,
       82,   82,  134,   82,  213,   82,  213,   82,   82,  213,
       82,   82,  213,   82,   82,   82,  135,   82,   82,  136,
       82,   82,  137,   82,  213,   82,   82,   82,   82,  138,

       82,  139,   82,   82,  213,   82,  140,   82,  213,   82,
       82,  213,  141,  142,  213,  142,   82,  213,  143,  143,
      143,  143,  143,  112,  112,  112,  112,  112,  114,  114,
      114,  114,  114,  213,   76,  114,  114,  114,  114,  114,
       81,   81,   81,   81,   81,   82,   76,  145,  213,  213,
       82,   82,   82,   82,   82,  132,  144,   82,   82,   82,
       82,   82,  148,  132,   82,   82,  149,   82,   82,   82,
      146,  147,  150,   82,  152,   82,   82,  153,   82,   82,
       82,   82,   82,   82,  151,   82,   82,   82,   82,   82,
       82,  154,   82,  132,   82,   82,   82,  155,   82,  156,

       82,   82,   82,   82,  213,   82,  213,   82,   82,   82,
      158,   82,   82,   82,   82,   82,  213,  159,   82,  161,
       82,  213,   82,   82,   82,   82,   82,   82,  162,   82,
       82,   82,  160,   82,  163,   82,  213,   82,   82,  132,
       82,  165,   82,  213,  213,  164,  213,  213,  213,   82,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
       82,   82,   82,   82,  213,   82,  213,   82,   82,   82,
       82,  132,   82,  166,   82,   82,   82,   82,   82,   82,
      132,   82,  167,   82,   82,   82,   82,  213,   82,   82,
       82,   82,   82,   82,  132,   82,   82,   82,   82,   82,

       82,  168,  169,   82,  174,  171,   82,  213,  213,   82,
       82,   82,  213,   82,  132,  172,   82,   82,   82,   82,
       82,  176,   82,   82,   82,  175,   82,   82,  213,   82,
       82,  213,  179,   82,  177,  178,   82,   82,   82,   82,
      180,   82,   82,  184,   82,   82,   82,  213,   82,  183,
      182,   82,   82,   82,  181,   82,   82,   82,   82,   82,
      213,   82,  186,   82,   82,   82,   82,  188,   82,  132,
       82,   82,   82,   82,   82,   82,  189,   82,   82,   82,
      213,   82,   82,  213,  191,   82,   82,  190,   82,   82,
      132,   82,   82,  213,   82,  213,   82,   82,  132,  213,

      132,   82,   82,  196,   82,   82,  213,  213,   82,   82,
       82,   82,  213,  192,  213,  132,   82,   82,  193,   81,
       81,  194,   81,   81,   82,   82,   82,   82,  198,  213,
       82,   82,   82,   82,   82,   82,  213,   82,   82,   82,
       82,   82,   82,   82,  200,  203,  199,  132,  213,   82,
       82,   81,   81,   81,   81,   81,   82,   82,  202,  213,
       82,   82,   82,   82,  213,  132,   82,   82,   82,  132,
       82,   82,  213,   82,   82,   82,   82,  207,   82,  204,
       82,  213,  213,  213,  213,   82,   55,   55,   55,   57,
       57,   57,   60,   60,   60,   64,   64,   64,   82,   82,

      116,  116,   11,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213
    } ;

static const flex_int16_t yy_chk[866] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,    7,    8,  219,    7,    8,  211,
        5,    6,   26,   26,   26,   26,   26,   27,   43,  209,
      208,  206,   27,  205,   29,   43,   29,   29,   29,   29,
       29,  203,   43,  201,    7,    8,    9,   29,   34,   34,

       34,   34,   34,   37,   37,   37,   37,   37,  195,   29,
      187,   38,   38,   38,   38,   38,  185,   40,   45,  173,
      170,   40,  157,  153,   40,   45,   39,   39,   39,   39,
       39,   40,   45,  133,    9,    9,    9,    9,    9,    9,
        9,    9,    9,   10,   38,   39,   38,   41,   47,   59,
       33,   32,   39,   42,   41,   47,   31,   25,   41,   39,
       42,   41,   47,   44,   42,   42,   51,   42,   44,   23,
       44,   19,   42,   51,   16,   44,   44,   44,   11,    4,
       51,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       28,   46,   28,   28,   28,   28,   28,   48,   46,    3,

       53,   48,    0,   28,   48,   46,   28,   53,   46,   49,
       82,   48,   50,   49,   53,   28,   49,   82,    0,   50,
        0,    0,    0,   49,   82,   53,   50,   49,    0,    0,
       49,    0,    0,   28,    0,   50,   70,   70,   70,   70,
       70,   73,   73,   73,   73,   73,    0,   70,   76,    0,
       76,    0,   73,   76,   76,   76,   76,   76,    0,   70,
        0,    0,    0,   74,   73,   74,   74,   74,   74,   74,
       81,   81,   81,   81,   81,    0,   74,   75,   83,   75,
       75,   75,   75,   75,    0,   83,   85,   84,   74,    0,
       75,   84,   83,   85,   84,    0,    0,   86,    0,   87,

       85,   84,   75,   85,   86,    0,   87,    0,   89,   88,
       90,   86,   87,   87,   88,   89,   88,   90,    0,   91,
       92,   90,   89,   88,   90,   89,   91,   92,   93,   95,
        0,    0,   94,   91,   92,   93,   95,    0,   92,   94,
      100,   96,   93,   95,   93,   94,   94,   95,   96,   97,
        0,   98,   99,    0,    0,   96,   97,    0,   98,   99,
        0,  100,    0,   97,   97,   98,   99,   99,  100,   98,
      101,  103,  101,  102,    0,  100,    0,  101,  103,    0,
      102,  104,    0,  105,  101,  103,  102,  102,  104,  103,
      105,  107,  104,  106,    0,  104,  108,  105,  107,  105,

      106,  106,  109,  108,    0,  107,  107,  106,    0,  109,
      108,    0,  108,  111,    0,  111,  109,    0,  111,  111,
      111,  111,  111,  112,  112,  112,  112,  112,  113,  113,
      113,  113,  113,    0,  112,  114,  114,  114,  114,  114,
      116,  116,  116,  116,  116,  117,  112,  118,    0,    0,
      120,  119,  117,  121,  118,  119,  117,  120,  119,  117,
      121,  118,  122,  120,  120,  119,  122,  121,  123,  122,
      121,  121,  123,  124,  125,  123,  122,  126,  127,  129,
      124,  125,  123,  130,  124,  127,  129,  124,  125,  128,
      130,  128,  127,  129,  132,  131,  128,  130,  126,  131,

      134,  132,  131,  128,    0,  126,    0,  134,  132,  131,
      134,  135,  126,  136,  134,  137,    0,  135,  135,  137,
      136,    0,  137,  139,  141,  135,  138,  136,  138,  137,
      139,  141,  136,  138,  138,  140,    0,  139,  141,  140,
      138,  139,  140,    0,    0,  138,    0,    0,    0,  140,
      142,  142,  142,  142,  142,  143,  143,  143,  143,  143,
      144,  145,  146,  148,    0,  147,    0,  144,  145,  146,
      148,  145,  147,  147,  144,  145,  146,  148,  149,  147,
      146,  150,  148,  151,  152,  149,  154,    0,  150,  155,
      151,  152,  149,  154,  149,  150,  155,  151,  152,  156,

      154,  151,  152,  155,  158,  155,  156,    0,    0,  160,
      159,  158,    0,  156,  159,  156,  160,  159,  158,  161,
      162,  161,  163,  160,  159,  160,  161,  162,    0,  163,
      164,    0,  164,  161,  162,  163,  163,  164,  165,  167,
      165,  166,  168,  169,  164,  165,  167,    0,  166,  168,
      167,  171,  165,  167,  166,  166,  168,  172,  171,  169,
        0,  174,  172,  175,  172,  171,  169,  174,  174,  171,
      175,  172,  176,  169,  177,  174,  175,  175,  178,  176,
        0,  177,  179,    0,  178,  178,  176,  177,  177,  179,
      176,  180,  178,    0,  181,    0,  179,  182,  180,    0,

      179,  181,  183,  186,  182,  180,    0,    0,  181,  183,
      186,  182,    0,  181,    0,  182,  183,  186,  183,  184,
      184,  184,  184,  184,  188,  189,  190,  191,  188,    0,
      193,  188,  189,  190,  191,  198,    0,  193,  188,  189,
      190,  191,  198,  192,  193,  199,  190,  192,    0,  198,
      192,  194,  194,  194,  194,  194,  196,  192,  196,    0,
      200,  202,  207,  196,    0,  202,  199,  200,  202,  207,
      196,  204,    0,  199,  200,  202,  207,  204,  204,  200,
      199,    0,    0,    0,    0,  204,  214,  214,  214,  215,
      215,  215,  216,  216,  216,  217,  217,  217,  218,  218,

      220,  220,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gocompiler.l"
#line 7 "gocompiler.l"
    #define yygetc() getc(yyin)

    int l = 1;               //Var for Line
    int column = 1;          //Var for Column
    int needs_semicolon = 0; //Var for Semicolon need
    int tokens=1;            //Var for printing all tokens (-l -> 1)
    int error = 0;

    void col(){
        column += yyleng;
    }
    void line(){
        l++;
        column=1;
    }
    void semicollon(int x){
        needs_semicolon = (x==1 ? 1 : 0); 
    }
#line 726 "lex.yy.c"
#line 28 "gocompiler.l"
 /*States*/

#line 730 "lex.yy.c"

#define INITIAL 0
#define LINE_COMMENT 1
#define MULTI_LINE_COMMENT 2
#define STRLIT 3
#define SEQUENCE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 30 "gocompiler.l"


 /*Comments*/
#line 955 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 214 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 803 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "gocompiler.l"
{BEGIN LINE_COMMENT;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 34 "gocompiler.l"
{BEGIN 0; line();}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "gocompiler.l"
{;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "gocompiler.l"
{ BEGIN MULTI_LINE_COMMENT; col();}
	YY_BREAK
case YY_STATE_EOF(MULTI_LINE_COMMENT):
#line 38 "gocompiler.l"
{printf("Line %d, column %d: unterminated comment\n",l,column); BEGIN 0;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "gocompiler.l"
{BEGIN 0; col();}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 40 "gocompiler.l"
{line();}  
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "gocompiler.l"
{col();}
	YY_BREAK
/*Keywords */
case 8:
YY_RULE_SETUP
#line 44 "gocompiler.l"
{if(tokens) printf("PACKAGE\n"); col(); semicollon(0);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "gocompiler.l"
{if(tokens) printf("RETURN\n"); col(); semicollon(0);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "gocompiler.l"
{if(tokens) printf("ELSE\n"); col(); semicollon(0);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "gocompiler.l"
{if(tokens) printf("IF\n"); col(); semicollon(0);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "gocompiler.l"
{if(tokens) printf("FOR\n"); col(); semicollon(0);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "gocompiler.l"
{if(tokens) printf("VAR\n"); col(); semicollon(0);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "gocompiler.l"
{if(tokens) printf("PRINT\n"); col(); semicollon(0);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "gocompiler.l"
{if(tokens) printf("FUNC\n"); col(); semicollon(0);} 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "gocompiler.l"
{if(tokens) printf("PARSEINT\n"); col(); semicollon(0);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "gocompiler.l"
{if(tokens) printf("CMDARGS\n"); col(); semicollon(0);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "gocompiler.l"
{if(tokens) printf("INT\n"); col(); semicollon(0);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "gocompiler.l"
{if(tokens) printf("FLOAT32\n"); col(); semicollon(0);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "gocompiler.l"
{if(tokens) printf("STRING\n"); col(); semicollon(0);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "gocompiler.l"
{if(tokens) printf("BOOL\n"); col(); semicollon(0);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "gocompiler.l"
{if(tokens) printf("RESERVED(%s)\n",yytext); col(); semicollon(0);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "gocompiler.l"
{if(tokens) printf("INTLIT(%s)\n",yytext); col(); semicollon(1);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "gocompiler.l"
{if(tokens) printf("REALIT(%s)\n",yytext); col(); semicollon(1);}
	YY_BREAK
/*Finish this*/
case 25:
YY_RULE_SETUP
#line 66 "gocompiler.l"
{BEGIN STRLIT;col();}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "gocompiler.l"
{if(error==0 && yyleng>0){ yytext[yyleng-1]='\0'; printf("REALIT(%s)\n",yytext);}col();error=0;BEGIN 0;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "gocompiler.l"
{BEGIN SEQUENCE; yymore();col();}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "gocompiler.l"
{yymore();col();}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 70 "gocompiler.l"
{BEGIN 0;line();printf("Line %d, column %d: unterminated string literal\n",l,column);}
	YY_BREAK
case YY_STATE_EOF(STRLIT):
#line 71 "gocompiler.l"
{BEGIN 0;printf("Line %d, column %d: unterminated string literal\n",l,column);return 1;}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 72 "gocompiler.l"
{error = 1; printf("Line %d, column %d: illegal character (\\%c)\n",l,column,yytext[yyleng-1]); col();BEGIN STRLIT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "gocompiler.l"
{yymore();col();BEGIN STRLIT;}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 74 "gocompiler.l"
{BEGIN 0;line();printf("Line %d, column %d: unterminated string literal\n",l,column);}
	YY_BREAK
case YY_STATE_EOF(SEQUENCE):
#line 75 "gocompiler.l"
{BEGIN 0;printf("Line %d, column %d: unterminated string literal\n",l,column);return 1;}
	YY_BREAK
/*Operators* & punctuation*/
case 33:
YY_RULE_SETUP
#line 78 "gocompiler.l"
{if(tokens) printf("SEMICOLON\n"); col();semicollon(0);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "gocompiler.l"
{if(tokens) printf("BLANKID\n"); col(); semicollon(0);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "gocompiler.l"
{if(tokens) printf("PLUS\n"); col(); semicollon(0);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "gocompiler.l"
{if(tokens) printf("MINUS\n"); col(); semicollon(0);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "gocompiler.l"
{if(tokens) printf("STAR\n"); col(); semicollon(0);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "gocompiler.l"
{if(tokens) printf("DIV\n"); col(); semicollon(0);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "gocompiler.l"
{if(tokens) printf("MOD\n"); col(); semicollon(0);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "gocompiler.l"
{if(tokens) printf("AND\n"); col(); semicollon(0);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "gocompiler.l"
{if(tokens) printf("OR\n"); col(); semicollon(0);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 87 "gocompiler.l"
{if(tokens) printf("LT\n"); col(); semicollon(0);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "gocompiler.l"
{if(tokens) printf("LE\n"); col(); semicollon(0);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 89 "gocompiler.l"
{if(tokens) printf("GT\n"); col(); semicollon(0);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "gocompiler.l"
{if(tokens) printf("GE\n"); col(); semicollon(0);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 91 "gocompiler.l"
{if(tokens) printf("ASSIGN\n"); col(); semicollon(0);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 92 "gocompiler.l"
{if(tokens) printf("EQ\n"); col(); semicollon(0);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 93 "gocompiler.l"
{if(tokens) printf("NE\n"); col(); semicollon(0);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 94 "gocompiler.l"
{if(tokens) printf("NOT\n"); col(); semicollon(0);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 95 "gocompiler.l"
{if(tokens) printf("COMMA\n"); col(); semicollon(0);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 96 "gocompiler.l"
{if(tokens) printf("LBRACE\n"); col(); semicollon(0);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 97 "gocompiler.l"
{if(tokens) printf("RBRACE\n"); col(); semicollon(1);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 98 "gocompiler.l"
{if(tokens) printf("LPAR\n"); col(); semicollon(0);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 99 "gocompiler.l"
{if(tokens) printf("RPAR\n"); col(); semicollon(1);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "gocompiler.l"
{if(tokens) printf("LSQ\n"); col(); semicollon(0);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "gocompiler.l"
{if(tokens) printf("RSQ\n"); col(); semicollon(1);}
	YY_BREAK
/*Identifier*/
case 57:
YY_RULE_SETUP
#line 105 "gocompiler.l"
{if(tokens) printf("ID(%s)\n",yytext); col(); semicollon(1);}
	YY_BREAK
/*Special Cases*/
case 58:
YY_RULE_SETUP
#line 108 "gocompiler.l"
{col();}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 109 "gocompiler.l"
{line(); if(needs_semicolon == 1){
					if(tokens) printf("SEMICOLON\n");
					needs_semicolon = 0;
			        }
                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINE_COMMENT):
#line 114 "gocompiler.l"
{ if(needs_semicolon == 1){
                if(tokens) printf("SEMICOLON\n"); 
                }
                return 0;
                }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 120 "gocompiler.l"
{printf("Line %d, column %d: illegal character (%s)\n",l,column,yytext); col(); semicollon(0); BEGIN 0;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 121 "gocompiler.l"
ECHO;
	YY_BREAK
#line 1359 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 214 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 214 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 213);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 121 "gocompiler.l"

int main(int argc, char* argv[])
{
    if(argv[1] != NULL) {
        tokens = 1;
        }
    yylex();
    return 0;
}

int yywrap()
{
return 1;
}

